version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: MassTransitJobConsumer/Dockerfile
    environment:
      ConnectionStrings__JobService: "host=postgres;user id=postgres;password=Password12!;database=JobService;"
    depends_on:
      - postgres
  postgres:
    image: "postgres:9.6"
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - 'elastic_data:/usr/share/elasticsearch/data'
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elastic_data:
  postgres_data: